name: "Terraform CD"

on:
  push:
    branches:
      - main

jobs:
  terraform-cd:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari branch main
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup CLI Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      # 3. Menjalankan LocalStack dengan Network Host agar port langsung terbuka penuh
      - name: Start LocalStack (v2.1.0)
        run: |
          docker run -d --name localstack --network=host localstack/localstack:2.1.0
          
          echo "Menunggu LocalStack v2.1.0 siap..."
          until curl -s http://localhost:4566/_localstack/health | grep -q '"s3": "available"\|"s3": "running"'; do
            sleep 3
          done
          echo "LocalStack v2.1.0 telah siap dan merespon!"

      # 4. Inisialisasi Terraform
      - name: Terraform Init
        run: terraform init -backend=false

      # 5. Jalankan Terraform Apply (Ditambahkan limit timeout agar tidak stuck selamanya jika ada anomali)
      - name: Terraform Apply
        run: timeout 120s terraform apply -auto-approve -no-color
