name: "Terraform CD"

on:
  push:
    branches:
      - main

jobs:
  terraform-cd:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    # Menjalankan LocalStack sebagai service container di dalam runner GitHub Actions
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3

    steps:
      # 1. Checkout kode dari branch main
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup CLI Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      # 3. Inisialisasi Terraform
      - name: Terraform Init
        run: terraform init -backend=false

      # 4. Jalankan Terraform Apply tanpa intervensi manual (-auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
